### ISSUE TITLE
One-click installation of HOPR Desktop and Myne Chat

### ISSUE THREAD

**Issue by tolbrino** [hoprnet/myne-chat#6]
HOPR Desktop is the user-friendly package which installs hoprd as a service on the target system and provides some management UI to help users start/stop/configure/inspect the local hoprd instance.

It comes with Myne Chat or pointers on how to use it, depending on the design of Myne Chat. 

# Target Platforms

## Required

- macOS 10.15
- macOS 11
- macOS 12
- Windows 10
- Windows 11

## Optional

If this is possible, Linux platform support would be nice as well.

- Ubuntu 21.10
- Ubuntu 20.04

# Definition of Done

- [ ] builds are automated through CI
- [ ] builds can be tested for any version by downloading the binary installer from CI and running it
- [ ] architecture of the app and its build process is documented
- [ ] hopr team has tested the installer

**Comment by mjadach-iv** [comment]
Closing issue as the myne-chat project is closed for the time being. 
Will need to reopen if we will be updating the repo.
